version: '3.8' 
services: 
  backend: 
    build: ./backend 
    container_name: youtube_backend 
    ports: 
      - "5000:5000" 
    env_file: 
      - ./backend/.env 
    networks: 
      - youtube_net 
    restart: unless-stopped 
 
  frontend: 
    build: ./frontend 
    container_name: youtube_frontend 
    ports: 
      - "3000:80" 
    env_file: 
      - ./frontend/.env 
    depends_on: 
      - backend 
    networks: 
      - youtube_net 
    restart: unless-stopped 
 
networks: 
  youtube_net:
